# -*- coding: utf-8 -*-
{
    'name': 'BSI EDI Interface',
    'version': '1.2503.2',
    'category': 'Tools',
    'description': u"""
BSI EDI Interface
""",
    'author': 'BUSINESS SYSTEMS INTEGRATORS, INC.',
    'price': 0.00,
    'currency': 'USD',
    'support': 'support@businesssysinteg.com',
    'depends': [
        'base','stock','sale','purchase','stock_delivery','delivery',
    ],
    'data': [
        'security/bsiedi_groups.xml',
        'security/bsiedi_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml', 
        'data/itemxref_data.xml',
        'data/shiptoxref_data.xml',
        'data/tradingpartner_data.xml',
        'data/releaseapproval_data.xml',
        'views/bsiedi_menuitems.xml',
        'views/itemxref_views.xml',
        'views/tradingpartner_views.xml',
        'views/shiptoxref_views.xml',
        'views/res_config_settings_views.xml',
        'views/purchase_views_inherit.xml',
        'views/sale_views_inherit.xml',
        'views/releaseapproval_views.xml',
        'data/inbshipviaxref_data.xml',
        'data/outbshipviaxref_data.xml',
        'views/inbshipviaxref_views.xml',
        'views/outbshipviaxref_views.xml',
        'views/res_partner_views_inherit.xml',
        'views/stock_picking_views_inherit.xml',
        'views/stock_warehouse_views_inherit.xml',
        'data/stock_picking_data.xml',
        'views/account_move_views_inherit.xml',
        'views/warehousetpcodes_views.xml',
        'data/warehousetpcodes_data.xml',
        'views/stock_location_views_inherit.xml',
        'views/delivery_carrier_views_inherited.xml',
        'views/product_views_inherit.xml',
        'views/carrieraccountoverrides_views.xml',
        'data/carrieraccountoverrides_data.xml',
    ],
    'demo': [
    ],
    'images': [
        'images/Portal_Screenshot.png',
        'images/Portal_Screenshot2.png',
        'images/HumanReadable_Screenshot.png',
        'images/RawData_Screenshot.png',
        'images/ShipmentBuilder_Screenshot.png',
        'images/GS1Label_Screenshot.png',
        'images/ConnectingYourWorld.png',
    ],
    'application': True,
    'license': 'OPL-1',
}
